#!/usr/bin/env python3
"""
cigar_stats.py - Analyze CIGAR strings with Regular Expressions and generate a report.

Part 4: Regular Expression Analysis of CIGAR Strings
Usage: python3 cigar_stats.py
Input:  alignments.tsv, distances.tsv  (generated by alignment.py)
Output: cigar_stats.tsv, report.txt
"""

import re
import sys


# ---------------------------------------------------------------------------
# Helper: count CIGAR operations using Regular Expressions
# ---------------------------------------------------------------------------

def count_cigar_ops(cigar):
    """
    Count each alignment operation in an expanded CIGAR string.

    Regular Expressions are particularly useful here because CIGAR strings
    are compact encodings of structured patterns.  re.findall() lets us
    extract all occurrences of a single character in one call, which is both
    concise and efficient.

    Returns a dict with keys 'M', 'I', 'D', 'X' mapped to their counts.
    """
    return {
        'M': len(re.findall(r'M', cigar)),   # Matches
        'I': len(re.findall(r'I', cigar)),   # Insertions
        'D': len(re.findall(r'D', cigar)),   # Deletions
        'X': len(re.findall(r'X', cigar)),   # Substitutions
    }


# ---------------------------------------------------------------------------
# Helper: read a tab-separated file (skip the header row)
# ---------------------------------------------------------------------------

def read_tsv(filepath):
    """Read a TSV file and return a list of row lists (header excluded)."""
    rows = []
    with open(filepath, 'r') as fh:
        lines = fh.readlines()
    for line in lines[1:]:          # skip header
        line = line.strip()
        if line:
            rows.append(line.split('\t'))
    return rows


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # Read alignments (Accession, Distance, CIGAR)
    align_rows = read_tsv('alignments.tsv')

    # Read distances for cross-reference (Accession, Distance)
    dist_rows = read_tsv('distances.tsv')
    distance_map = {row[0]: int(row[1]) for row in dist_rows}

    # Compute per-sequence CIGAR statistics
    # stats[i] = (accession, distance, M, I, D, X)
    stats = []
    for row in align_rows:
        accession = row[0]
        distance  = int(row[1])
        cigar     = row[2]
        counts = count_cigar_ops(cigar)
        stats.append((accession, distance,
                       counts['M'], counts['I'], counts['D'], counts['X']))

    # -----------------------------------------------------------------------
    # Write cigar_stats.tsv
    # -----------------------------------------------------------------------
    with open('cigar_stats.tsv', 'w') as f:
        f.write('Accession\tM\tI\tD\tX\n')
        for accession, distance, m, i, d, x in stats:
            f.write(f'{accession}\t{m}\t{i}\t{d}\t{x}\n')

    # -----------------------------------------------------------------------
    # Generate report.txt
    # -----------------------------------------------------------------------

    # Sequence with the smallest edit distance
    min_dist_entry = min(stats, key=lambda s: s[1])
    # Sequence with the largest edit distance
    max_dist_entry = max(stats, key=lambda s: s[1])
    # Sequence with the largest number of matches
    max_match_entry = max(stats, key=lambda s: s[2])

    def format_entry(label, entry):
        accession, distance, m, i, d, x = entry
        return (
            f"{label}:\n"
            f"{accession}\n"
            f"Distance: {distance}\n"
            f"Matches: {m}\n"
            f"Insertions: {i}\n"
            f"Deletions: {d}\n"
            f"Substitutions: {x}\n"
        )

    with open('report.txt', 'w') as f:
        f.write(format_entry("Sequence with smallest edit distance", min_dist_entry))
        f.write('\n')
        f.write(format_entry("Sequence with largest edit distance", max_dist_entry))
        f.write('\n')
        f.write(format_entry("Sequence with largest number of matches", max_match_entry))

    print(f"Processed {len(stats)} sequences.")
    print("Output written to cigar_stats.tsv and report.txt")


if __name__ == '__main__':
    main()
